#!/bin/bash
# migrate_zettelkasten.sh - Script simple de migración
# REVISAR CADA COMANDO ANTES DE EJECUTAR
# 
# Este script migra todos los zettels existentes a la nueva estructura Luhmann
# basada en la arquitectura documentada y respetando la evolución cronológica

echo "========================================="
echo "Iniciando migración de zettelkasten..."
echo "REVISAR CADA COMANDO ANTES DE EJECUTAR"
echo "========================================="
echo ""

echo "🔄 Migrando zettel raíz..."
mv "1 - adopcion de vibedoc.md" "1a - adopcion vibedoc inicial.md"

echo "🔄 Migrando arquitectura y estructura..."
mv "1.2.1 - estructura de directorios python.md" "2a - estructura directorios python.md"
mv "1.2.1.1 - decisiones estructura directorios python.md" "2a1 - decisiones estructura directorios.md"
mv "1.2.2 - implementacion de abstracciones.md" "2b - implementacion abstracciones.md"
mv "1.2.2.1 - incorporar github actions para unitetests.md" "2b1 - incorporar github actions unitetests.md"
mv "1.2.2.2 - decisiones implementacion abstracciones.md" "2b2 - decisiones implementacion abstracciones.md"
mv "1.2.2.3 - reflexion implementacion abstracciones.md" "2b3 - reflexion implementacion abstracciones.md"

echo "🔄 Migrando comandos base..."
mv "1.2.3 - comandos base.md" "3a - comandos base.md"
mv "1.2.3.1 - patrones manejo errores gitinterface.md" "3a1 - patrones manejo errores gitinterface.md"
mv "1.2.3.1 - reflexion implementacion gitinterface.md" "3a2 - reflexion implementacion gitinterface.md"
mv "1.2.3.2 - ajustes alcance commitcommand.md" "3a3 - ajustes alcance commitcommand.md"
mv "1.2.3.2 - reflexion implementacion commitcommand.md" "3a4 - reflexion implementacion commitcommand.md"
mv "1.2.3.3 - analisis alcance loggingmanager.md" "3a5 - analisis alcance loggingmanager.md"
mv "1.2.3.3 - reflexion implementacion loggingmanager.md" "3a6 - reflexion implementacion loggingmanager.md"

echo "🔄 Migrando configuración..."
mv "1.2.4 - analisis serie historias configuracion.md" "4a - analisis serie historias configuracion.md"
mv "1.2.4 - comando de configuracion.md" "4a1 - comando de configuracion.md"
mv "1.2.4.1 - reflexion implementacion configmanager-basico.md" "4a2 - reflexion implementacion configmanager-basico.md"
mv "1.2.4.1 - reflexion limitaciones vibedoc planificacion anticipada.md" "4a3 - reflexion limitaciones vibedoc planificacion.md"
mv "1.2.4.2 - reflexion implementacion validacion-esquemas.md" "4a4 - reflexion implementacion validacion-esquemas.md"
mv "1.2.4.3 - reflexion implementacion configcommand-execute.md" "4a5 - reflexion implementacion configcommand-execute.md"
mv "1.2.4.4 - reflexion implementacion funcionalidades-avanzadas-config.md" "4a6 - reflexion funcionalidades-avanzadas-config.md"

echo "🔄 Migrando comandos específicos..."
mv "1.2.5 - comandos especificos.md" "3b - comandos especificos.md"
mv "1.2.5.1 - analisis inconsistencias documentacion-codigo.md" "3b1 - analisis inconsistencias documentacion-codigo.md"
mv "1.2.5.1 - integracion de comandos especificos con ia.md" "3b2 - integracion comandos especificos con ia.md"
mv "1.2.5.1.1 - analisis inconsistencias story-1.2.5.1.md" "3b3 - analisis inconsistencias story-1.2.5.1.md"
mv "1.2.5.1.2 - decisiones story-1.2.5.1.md" "3b4 - decisiones story-1.2.5.1.md"
mv "1.2.5.1.3 - reflexion implementacion comandos-conventional-commits-basicos.md" "3b5 - reflexion comandos-conventional-commits-basicos.md"
mv "1.2.5.2 - analisis arquitectura comandos especializados.md" "3b6 - analisis arquitectura comandos especializados.md"
mv "1.2.5.2.1 - analisis inconsistencias story-1.2.5.2.md" "3b7 - analisis inconsistencias story-1.2.5.2.md"
mv "1.2.5.2.2 - decisiones story-1.2.5.2.md" "3b8 - decisiones story-1.2.5.2.md"
mv "1.2.5.2.3 - reflexion implementacion comandos-conventional-commits-especializados.md" "3b9 - reflexion comandos-conventional-commits-especializados.md"

echo "🔄 Migrando comandos utilidad Git..."
mv "1.2.5.3 - analisis comandos utilidad git avanzados.md" "3c - analisis comandos utilidad git avanzados.md"
mv "1.2.5.3.1 - analisis inconsistencias story-1.2.5.3.md" "3c1 - analisis inconsistencias story-1.2.5.3.md"
mv "1.2.5.3.2 - decisiones story-1.2.5.3.md" "3c2 - decisiones story-1.2.5.3.md"
mv "1.2.5.3.3 - reflexion implementacion comandos-utilidad-git-basicos.md" "3c3 - reflexion comandos-utilidad-git-basicos.md"

echo "🔄 Migrando comandos navegación ramas..."
mv "1.2.5.4.1 - analisis inconsistencias story-1.2.5.4.md" "3d1 - analisis inconsistencias story-1.2.5.4.md"
mv "1.2.5.4.2 - decisiones story-1.2.5.4.md" "3d2 - decisiones story-1.2.5.4.md"
mv "1.2.5.4.3 - reflexion implementacion comandos-navegacion-ramas.md" "3d3 - reflexion comandos-navegacion-ramas.md"

echo "🔄 Migrando comandos gestión ramas avanzada..."
mv "1.2.5.5.1 - analisis inconsistencias story-1.2.5.5.md" "3e1 - analisis inconsistencias story-1.2.5.5.md"
mv "1.2.5.5.2 - decisiones story-1.2.5.5.md" "3e2 - decisiones story-1.2.5.5.md"
mv "1.2.5.5.3 - reflexion implementacion comandos-gestion-ramas-avanzada.md" "3e3 - reflexion comandos-gestion-ramas-avanzada.md"

echo "🔄 Migrando comandos interactivos..."
mv "1.2.5.6.1 - analisis inconsistencias story-1.2.5.6.md" "3f1 - analisis inconsistencias story-1.2.5.6.md"
mv "1.2.5.6.2 - decisiones story-1.2.5.6.md" "3f2 - decisiones story-1.2.5.6.md"
mv "1.2.5.6.3 - reflexion implementacion comandos-interactivos.md" "3f3 - reflexion comandos-interactivos.md"

echo "🔄 Migrando IA y comandos relacionados..."
mv "1.2.6 - el comando ggai.md" "9a - comando ggai.md"
mv "1.2.6.1 - parametro-ai-pendiente.md" "9a1 - parametro-ai-pendiente.md"
mv "1.2.6.2 - validador-contexto-inteligente-ia.md" "9a2 - validador-contexto-inteligente-ia.md"
mv "1.2.6.3 - analisis-comprehensivo-integracion-ia.md" "9a3 - analisis-comprehensivo-integracion-ia.md"
mv "1.2.6.4 - decisiones-comando-sin-argumentos-ia.md" "9a4 - decisiones-comando-sin-argumentos-ia.md"
mv "1.2.6.5 - configuraciones-ia-detalladas.md" "9a5 - configuraciones-ia-detalladas.md"
mv "1.2.6.6 - mvp-ia-con-ux-mejorada.md" "9a6 - mvp-ia-con-ux-mejorada.md"
mv "1.2.6.7 - propuesta-ajustada-configuracion-existente.md" "9a7 - propuesta-ajustada-configuracion-existente.md"
mv "1.2.6.8 - mvp-final-ia.md" "9a8 - mvp-final-ia.md"

echo "🔄 Migrando instalación y dependencias..."
mv "1.2.7 - soporte para conda e instalacion de dependencias.md" "6a - soporte conda instalacion dependencias.md"
mv "1.2.7.1 - analisis dependencias y ambientes.md" "6a1 - analisis dependencias y ambientes.md"
mv "1.2.7.1.1 - decisiones-configuracion-ia-basica.md" "9b1 - decisiones-configuracion-ia-basica.md"
mv "1.2.7.1.2 - reflexion-configuracion-ia-basica.md" "9b2 - reflexion-configuracion-ia-basica.md"
mv "1.2.7.2 - resumen implementacion dependencias.md" "6a2 - resumen implementacion dependencias.md"
mv "1.2.7.2.1 - decisiones-analisis-complejidad.md" "9b3 - decisiones-analisis-complejidad.md"
mv "1.2.7.2.2 - reflexion-analisis-complejidad.md" "9b4 - reflexion-analisis-complejidad.md"
mv "1.2.7.3 - reflexion.md" "6a3 - reflexion implementacion dependencias.md"
mv "1.2.7.3.1 - decisiones-comando-ggai-basico.md" "9b5 - decisiones-comando-ggai-basico.md"
mv "1.2.7.3.2 - reflexion-comando-ggai-basico.md" "9b6 - reflexion-comando-ggai-basico.md"
mv "1.2.7.4.1 - decisiones-integracion-comandos-existentes.md" "9b7 - decisiones-integracion-comandos-existentes.md"
mv "1.2.7.4.2 - reflexion-integracion-comandos-existentes.md" "9b8 - reflexion-integracion-comandos-existentes.md"

echo "🔄 Migrando reflexiones finales..."
mv "1.3 - reflexion-final-iniciativa-adopcion-vibedoc.md" "1b - reflexion-final-iniciativa-adopcion-vibedoc.md"
mv "1.4 - reflexion-documentacion-configuracion-ia.md" "1c - reflexion-documentacion-configuracion-ia.md"

echo "🔄 Migrando mejoras metodológicas Vibedoc..."
mv "2.1 - procesos validacion documentacion-codigo.md" "1d - procesos validacion documentacion-codigo.md"
mv "2.2 - sincronizacion entre zettels.md" "1e - sincronizacion entre zettels.md"
mv "2.3 - plantillas guias zettels.md" "1f - plantillas guias zettels.md"
mv "2.4 - revisiones periodicas consistencia.md" "1g - revisiones periodicas consistencia.md"

echo "🔄 Migrando ideas futuras..."
mv "3.1 - ia-avanzada-futuro.md" "9c - ia-avanzada-futuro.md"
mv "3.2 - spinner-progreso-ia.md" "9c1 - spinner-progreso-ia.md"

echo "🔄 Migrando documentación inicial..."
mv "1.1 - documentacion inicial de ggGit con vibedoc.md" "1a1 - documentacion inicial ggGit vibedoc.md"
mv "1.2 - primeras ideas por adopcion de vibedoc.md" "1a2 - primeras ideas adopcion vibedoc.md"

echo ""
echo "========================================="
echo "Migración completada."
echo "REVISAR RESULTADOS ANTES DE git add"
echo "========================================="
echo ""
echo "Verificar que todos los archivos se movieron correctamente:"
echo "- Contar archivos antes y después"
echo "- Verificar que no hay archivos duplicados"
echo "- Comprobar que la estructura tiene sentido"
echo ""
echo "Si todo está correcto, ejecutar:"
echo "  git add ."
echo "  git commit -m 'Reorganizar zettelkasten: migración a sistema Luhmann basado en arquitectura'"
