# These are supported funding model platforms

github: [novafuria]
# ko_fi: # Replace with up to 4 Ko-fi usernames
# open_collective: # Replace with up to 4 Open Collective usernames
# patreon: # Replace with up to 4 Patreon usernames
# tidelift: # Replace with up to 4 Tidelift usernames
# community_bridge: # Replace with up to 4 Community Bridge project names
# liberapay: # Replace with up to 4 Liberapay usernames
# issuehunt: # Replace with up to 4 IssueHunt usernames
# otechie: # Replace with up to 4 Otechie usernames
# custom: # Replace with up to 4 custom sponsorship URLs
