name: gggit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - click>=8.0.0
  - pyyaml>=6.0
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - pip
  - pip:
    - colorama  # Para colores multiplataforma
