#!/bin/bash

source $(dirname $0)/_utils.sh

print_usage() {
    print_text "NAME"
    print_text "    ggdif - Show changes between commits, commit and working tree, etc"
    print_text ""
    print_text "SYNOPSIS"
    print_text "    ggdif [<options>] [--] [<pathspec>...]"
    print_text ""
    print_text "DESCRIPTION"
    print_text "    This command shows changes between commits, commit and working tree, etc."
    print_text ""
    print_text "OPTIONS"
    print_text "    [<options>] [--] [<pathspec>...]"
    print_text "        Same as git diff"
    print_text "    -h, --help"
    print_text "        Display this help message"
}

main() {
    git diff --color-words "$@"
}

if [ "$#" -eq 0 ]; then
    main
    exit
fi

while [ "$1" != "" ]; do
    case $1 in
        -h | --help )           print_usage
                                exit
                                ;;
        * )                     main "$@"
                                exit 1
    esac
    shift
done
