#!/bin/bash

source $(dirname $0)/_utils.sh

print_usage() {
    print_text "NAME"
    print_text "    ggl - Show git log"
    print_text ""
    print_text "SYNOPSIS"
    print_text "    ggl [<options>] [--] [<pathspec>...]"
    print_text ""
    print_text "DESCRIPTION"
    print_text "    This command shows git log."
    print_text ""
    print_text "OPTIONS"
    print_text "    [<options>] [--] [<pathspec>...]"
    print_text "        Same as git log"
    print_text "    -h, --help"
    print_text "        Display this help message"
}

main() {
    git log --oneline --graph --all --decorate "$@"
}

if [ "$#" -eq 0 ]; then
    main
    exit
fi

while [ "$1" != "" ]; do
    case $1 in
        -h | --help )           print_usage
                                exit
                                ;;
        * )                     main "$@"
                                exit 1
    esac
    shift
done
