#!/bin/bash

source $(dirname $0)/_utils.sh

print_usage() {
    print_text "NAME"
    print_text "    ggmaster - Checkout master branch"
    print_text ""
    print_text "SYNOPSIS"
    print_text "    ggmaster"
    print_text ""
    print_text "DESCRIPTION"
    print_text "    This command checks out the master branch."
    print_text ""
    print_text "OPTIONS"
    print_text "    -h, --help"
    print_text "        Display this help message"
}

main() {
    git checkout master
}

if [ "$#" -eq 0 ]; then
    main
    exit
fi

while [ "$1" != "" ]; do
    case $1 in
        -h | --help )           print_usage
                                exit
                                ;;
        * )                     print_invalid_argument
                                exit 1
    esac
    shift
done
