version: "1.0"

git:
  default_branch: "main"
  commit_template: "{type}({scope}): {description}"

conventional_commits:
  scopes: []
  require_scope: false
  custom_types: []

ai:
  enabled: false
  provider: "openai"
  api_key_env: "OPENAI_API_KEY"
  model: "gpt-3.5-turbo"

ui:
  colors:
    success: "green"
    error: "red"
    warning: "yellow"
    info: "blue"
  verbose: false
  quiet: false
