type: object
properties:
  version:
    type: string
    pattern: "^[0-9]+\\.[0-9]+$"
    description: "Versión del esquema de configuración"
  
  git:
    type: object
    properties:
      default_branch:
        type: string
        default: "main"
        description: "Rama por defecto del repositorio"
      commit_template:
        type: string
        default: "{type}({scope}): {description}"
        description: "Template para mensajes de commit"
  
  conventional_commits:
    type: object
    properties:
      scopes:
        type: array
        items:
          type: string
        description: "Scopes permitidos para commits (opcional)"
      require_scope:
        type: boolean
        default: false
        description: "Si se requiere scope en todos los commits"
      custom_types:
        type: array
        items:
          type: string
        description: "Tipos de commit personalizados adicionales (opcional)"
  
  ai:
    type: object
    properties:
      enabled:
        type: boolean
        default: false
        description: "Habilitar funcionalidades de IA"
      provider:
        type: string
        enum: ["openai", "anthropic", "azure", "local"]
        default: "openai"
        description: "Proveedor de servicios de IA (API compatible con OpenAI)"
      api_key_env:
        type: string
        default: "OPENAI_API_KEY"
        description: "Variable de entorno para API key"
      model:
        type: string
        default: "gpt-3.5-turbo"
        description: "Modelo de IA a utilizar"
      base_url:
        type: string
        description: "URL base para proveedores alternativos (opcional)"
      cost_limit:
        type: number
        default: 5.00
        minimum: 0
        description: "Límite de costo en USD por período"
      tracking_enabled:
        type: boolean
        default: true
        description: "Habilitar tracking de consumo de IA"
      usage_file:
        type: string
        default: ".gggit/ai-usage.yaml"
        description: "Archivo para tracking de consumo de IA"
      analysis:
        type: object
        properties:
          max_files:
            type: integer
            default: 10
            minimum: 1
            description: "Máximo número de archivos para análisis de complejidad"
          max_diff_lines:
            type: integer
            default: 200
            minimum: 1
            description: "Máximo número de líneas de diff para análisis de complejidad"
          max_file_size:
            type: integer
            default: 5000
            minimum: 1
            description: "Máximo tamaño de archivo en bytes para análisis de complejidad"
        required: ["max_files", "max_diff_lines", "max_file_size"]
  
  ui:
    type: object
    properties:
      colors:
        type: object
        properties:
          success:
            type: string
            default: "green"
          error:
            type: string
            default: "red"
          warning:
            type: string
            default: "yellow"
          info:
            type: string
            default: "blue"
      verbose:
        type: boolean
        default: false
        description: "Modo verboso para salida detallada"
      quiet:
        type: boolean
        default: false
        description: "Modo silencioso para salida mínima"

required: ["version"]
