name: Cross-Platform Testing

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled, unlabeled]
  workflow_dispatch:

jobs:
  test-linux:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash -el {0}
    env:
      PYTHONPATH: .

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.12'
        channels: conda-forge,defaults
        channel-priority: strict
        environment-file: environment.yml
        activate-environment: gggit

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Test on Ubuntu
      run: |
        bash health-check.sh
        pytest tests/
        
  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    
    defaults:
      run:
        shell: bash -el {0}
    env:
      PYTHONPATH: .

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.12'
        channels: conda-forge,defaults
        channel-priority: strict
        environment-file: environment.yml
        activate-environment: gggit

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Test on macOS
      run: |
        bash health-check.sh
        pytest tests/
